config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  resources :users, only: [:show,:index,:edit,:update]
  resources :books, only: [:create,:show,:index,:edit,:update,:destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create,:destroy]
  end
  root 'homes#top'
  get 'home/about', to: 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title,presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true, uniqueness: {scope: :book_id}
  validates :book_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   	attachment :profile_image
	validates :name, presence: true, length: {minimum: 2, maximum: 20}
	validates :introduction, length: {maximum: 50}
	has_many :books, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :book_comments

	def already_favorited?(book)
		self.favorites.exists?(book_id: book.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	# def create 修正用
	# 	@comment = BookComment.new(comment_params)
	# 	@comment.user_id = current_user.id
	# 	if @comment.save
	# 		redirect_back(fallback_location: root_path)
	# 	else
	# 		redirect_back(fallback_location: root_path)
	# 	end
	# end

	def create
		@book = Book.find(params[:book_id])
		@comment = @book.book_comments.new(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to book_path(@comment.book)
		else
    		@comments = @book.book_comments
			render 'books/show'
		end
	end

	def destroy
		@book = Book.find(params[:book_id])
		@comment = BookComment.find(params[:id])
		@comment.destroy
		redirect_to book_path(@comment.book)
	end

		private
		# def comment_params　修正用
		# 	params.require(:book_comment).permit(:content,:book_id)
		# end

		def comment_params
			params.require(:book_comment).permit(:content,:book_id)
		end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :baria_book, only: [:edit]

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
    @comments = @book.book_comments
    @comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
      flash[:notice] = 'You have creatad book successfully.'
  		redirect_to book_path(@book)
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book)
  	else
  		@book = Book.find(params[:id])
  		render 'edit'
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to user_path(book.user)
  end

	  private
	  def book_params
	  	params.require(:book).permit(:title,:body)
	  end

    def baria_book
      @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@favorite = current_user.favorites.create(book_id:params[:book_id])
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@book = Book.find(params[:book_id])
		@favorite = current_user.favorites.find_by(book_id:@book.id)
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :baria_user, only: [:edit]

  def index
  	@users = User.all
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "You have updated user successfully."
  		redirect_to user_path(@user)
  	else
  		render 'edit'
  	end
  end

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
    @books = Book.where(user_id:@user.id)
  end

	  private
	  def user_params
	  	params.require(:user).permit(:name,:introduction,:profile_image)
	  end

    def baria_user
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h1>New book</h1>
<%= form_for(book) do |f| %>
	
	<%= f.label :title %></br>
	<%= f.text_field :title, autofocus: true %></br>

	<%= f.label :opinion %></br>
	<%= f.text_area :body, autofucus: true %>

	<%= f.submit class: "btn btn-primary form-control" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>

				<%= f.label :title %></br>
				<%= f.text_field :title, class: "form-control" %></br>

				<%= f.label :opinion %></br>
				<%= f.text_area :body, class: "form-control" %></br>

				<%= f.submit class: "form-control btn btn-primary" %>

			<% end%>
			<%= link_to 'Show',book_path(@book) %> | <%= link_to 'Back',books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', object: @book %>

<div class="container">
	<div class="row">
		<div class="col-xs-3 col-md-3">
			<h1>User info</h1>
			<%= render "users/info" ,user:current_user%>
		</div>
		<div class="col-xs-9 col-md-9">
			<h1>Books</h1>
			<table class= "table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Option</th>
						<th></th>
					</tr>
				</thead>

				<% @books.each do |book| %>
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(book.user) do %>
									<%= attachment_image_tag(book.user ,:profile_image, :fill,30,30 ,fallback: "no_image.jpg") %>
								<% end %>
							</td>
							<td><%= link_to book.title, book_path(book) %></td>
							<td><%= book.body %></td>
							<td>
								<% if current_user.already_favorited?(book) %>
									<%= link_to book_favorites_path(book) ,method: :delete do %>
										<i class="fas fa-heart"></i>
									<% end %>
								<% else %>
									<%= link_to book_favorites_path(book) ,method: :post do %>
										<i class="far fa-heart"></i>
									<% end %>
								<% end %>
								<%= book.favorites.count %>件
							</td>
						</tr>
					</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3 col-md-3">
			<h1>User info</h1>
			<%= render "users/info" ,user:@book.user%>
		</div>
		<div class="col-xs-9 col-md-9">
			<h1>Book detail</h1>
			<table class= "table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Option</th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
					<tbody>
						<tr>
							<td><%= link_to user_path(@book.user) do %>
									<%= attachment_image_tag(@book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg") %><br>
									<%= @book.user.name %>
								<% end %>
							</td>
							<td><%= @book.title %></td>
							<td><%= @book.body %></td>
							<% if current_user == @book.user %>
								<td><%= link_to "Edit", edit_book_path(@book),class: "btn btn-success" %></td>
								<td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger" %></td>
								<td>
								<% if current_user.already_favorited?(@book) %>
									<%= link_to book_favorites_path(@book) ,method: :delete do %>
										<i class="fas fa-heart"></i>
									<% end %>
								<% else %>
									<%= link_to book_favorites_path(@book) ,method: :post do %>
										<i class="far fa-heart"></i>
									<% end %>
								<% end %>
								<%= @book.favorites.count %>件
							</td>
							<% end %>
						</tr>
					</tbody>
			</table>
			<% @comments.each do |comment| %>
			<div>
				<%= link_to user_path(comment.user) do %>
					<%= attachment_image_tag comment.user, :profile_image, :fill,30,30 ,fallback: "no_image.jpg" %>
				<% end %>
				<%= comment.content %>
				<%= link_to "Destroy", book_book_comment_path(@book,comment), method: :delete, class: "btn btn-denger" %>
			</div>
			<% end %>

			<%= form_for [@book,@comment], url: book_book_comments_path(@book) do |f| %>

				<%= f.text_area :content, autofocus: true %></br>

				<%= f.submit "コメントする" %>
				<% end %>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6-offset-3">
			<h1>welcome to Bookers !!</h1>
			<p>In Bookers,

			you can share and exchange your opinions , inpressions , and emotions

			about various books!</p>

			<% if user_signed_in? %>
				<div class="row">
					<%= link_to 'Log in',user_path(current_user),class: "btn btn-info form-control" %>
				</div>
				<div class="row">
					<%= link_to 'Sign up',user_path(current_user), class: "btn btn-success form-control"%>
				</div>
				<% else %>
				<div class="row">
					<%= link_to 'Log in',new_user_session_path,class: "btn btn-info form-control" %>
				</div>
				<div class="row">
					<%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success form-control" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
    <div class="alert alert-danger">
    	<%= pluralize(object.errors.count,"error") %> prohibited this obj from being saved:
    </div>
    <ul>
    	<% object.errors.full_messages.each do |obj| %>
    		<li><%= obj %></li>
    	<% end %>
    </ul>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<!-- <header class= "navbar navbar-inverse">
	<div class= "containar"> -->
		<nav class= "nav navbar-nav navbar-left">
			<span class="navbar-brand">Bookers2-re</span>
		</nav>
		<nav>
			<ul class= "nav navbar-nav navbar-right ">
					<% if user_signed_in?%>
						<li><%= link_to 'Home',user_path(current_user) %></li>
						<li><%= link_to 'Users',users_path %></li>
						<li><%= link_to 'Books', books_path %></li>
						<li><%= link_to 'logout',destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to 'Home',root_path %></li>
						<li><%= link_to 'About',home_about_path %></li>
						<li><%= link_to 'sign up',new_user_registration_path %></li>
						<li><%= link_to 'login',new_user_session_path %></li>
					<% end %>
			</ul>
		</nav>
	<!-- </div>
</header> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Re</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <%= render 'layouts/header' %>
      </div>
    </nav>
    <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_info.html.erb
		<table class= "table">
			<tr><%= attachment_image_tag user, :profile_image, :fill,30,30, fallback: "no_image.jpg" %></tr></br>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= user.introduction %></th>
			</tr>
		</table>

		<%= link_to edit_user_path(user) ,class: "btn btn-success form-control" do %>
			 <i class="fas fa-wrench"></i>
		<% end %>

		<%= render 'books/new', book:Book.new%>

app/views/users/edit.html.erb
<%= render 'layouts/errors', object: @user %>

<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>User info</h1>
			<%= form_for(@user) do |f| %>

				<%= f.label :name %></br>
				<%= f.text_field :name, placeholder: @user.name, autofocus: true, class: "form-control" %></br>

				<%= f.label :profile_image %></br>
				<%= f.attachment_field :profile_image %></br>

				<%= f.label :introduction %></br>
				<%= f.text_area :introduction, class: "form-control" %></br>

				<%= f.submit class: "form-control btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3 col-md-3">
			<h1>User info</h1>
			<%= render "info" ,user:current_user%>
		</div>
		<div class="col-xs-9 col-md-9">
			<h1>Users</h1>
				<table class="table table-inverse">
					<thead>
						<tr>
							<th>Image</th>
							<th>Name</th>
							<th></th>
						</tr>
					</thead>
					<% @users.each do |user| %>
						<tbody>
							<tr>
								<td><%= attachment_image_tag user, :profile_image ,:fill,30,30 ,fallback: "no_image.jpg" %></td>
								<td><%= user.name %></td>
								<td><%= link_to 'Show',user_path(user) %></td>
							</tr>
						</tbody>
					<% end %>
				</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3 col-md-3">
			<h1>User info</h1>
			<%= render "info" ,user:@user%>
		</div>
		
		<div class="col-xs-9 col-md-9">
			<h1>User</h1>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user) do %>
									<%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><br>
								<% end %>
							</td>
							<td><%= link_to book.title, book_path(book) %></td>
							<td><%= book.body %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>